// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"

class Vtop__Syms;

class Vtop___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk_i,0,0);
        VL_IN8(rst_ni,0,0);
        CData/*0:0*/ top__DOT__pipelined__DOT__id_reset_n;
        CData/*0:0*/ top__DOT__pipelined__DOT__ex_reset_n;
        CData/*0:0*/ top__DOT__pipelined__DOT__mem_reset_n;
        CData/*0:0*/ top__DOT__pipelined__DOT__wb_reset_n;
        CData/*0:0*/ top__DOT__pipelined__DOT__pc_enable;
        CData/*0:0*/ top__DOT__pipelined__DOT__br_sel;
        CData/*0:0*/ top__DOT__pipelined__DOT____Vcellout__ex_reg1__is_rs2_o;
        CData/*1:0*/ top__DOT__pipelined__DOT____Vcellout__ex_reg1__wb_sel_o;
        CData/*0:0*/ top__DOT__pipelined__DOT____Vcellout__ex_reg1__is_load_o;
        CData/*0:0*/ top__DOT__pipelined__DOT____Vcellout__ex_reg1__mem_wren_o;
        CData/*2:0*/ top__DOT__pipelined__DOT____Vcellout__ex_reg1__mem_op_o;
        CData/*0:0*/ top__DOT__pipelined__DOT____Vcellout__ex_reg1__br_unsigned_o;
        CData/*0:0*/ top__DOT__pipelined__DOT____Vcellout__ex_reg1__op_b_sel_o;
        CData/*0:0*/ top__DOT__pipelined__DOT____Vcellout__ex_reg1__op_a_sel_o;
        CData/*3:0*/ top__DOT__pipelined__DOT____Vcellout__ex_reg1__alu_op_o;
        CData/*0:0*/ top__DOT__pipelined__DOT____Vcellout__ex_reg1__rd_wren_o;
        CData/*1:0*/ top__DOT__pipelined__DOT____Vcellout__mem_reg1__wb_sel_o;
        CData/*0:0*/ top__DOT__pipelined__DOT____Vcellout__mem_reg1__is_load_o;
        CData/*0:0*/ top__DOT__pipelined__DOT____Vcellout__mem_reg1__mem_wren_o;
        CData/*2:0*/ top__DOT__pipelined__DOT____Vcellout__mem_reg1__mem_op_o;
        CData/*0:0*/ top__DOT__pipelined__DOT____Vcellout__mem_reg1__rd_wren_o;
        CData/*1:0*/ top__DOT__pipelined__DOT____Vcellout__wb_reg1__wb_sel_o;
        CData/*0:0*/ top__DOT__pipelined__DOT____Vcellout__wb_reg1__is_load_o;
        CData/*0:0*/ top__DOT__pipelined__DOT____Vcellout__wb_reg1__mem_wren_o;
        CData/*0:0*/ top__DOT__pipelined__DOT____Vcellout__wb_reg1__rd_wren_o;
        CData/*0:0*/ top__DOT__pipelined__DOT____Vcellout__hazard_detect1__wb_enable_o;
        CData/*0:0*/ top__DOT__pipelined__DOT____Vcellout__hazard_detect1__mem_enable_o;
        CData/*0:0*/ top__DOT__pipelined__DOT____Vcellout__hazard_detect1__ex_enable_o;
        CData/*0:0*/ top__DOT__pipelined__DOT____Vcellout__hazard_detect1__id_enable_o;
        CData/*0:0*/ top__DOT__pipelined__DOT____Vcellout__ctr_unit1__is_rs2_o;
        CData/*1:0*/ top__DOT__pipelined__DOT____Vcellout__ctr_unit1__wb_sel_o;
        CData/*2:0*/ top__DOT__pipelined__DOT____Vcellout__ctr_unit1__mem_op_o;
        CData/*3:0*/ top__DOT__pipelined__DOT____Vcellout__ctr_unit1__alu_op_o;
        CData/*0:0*/ top__DOT__pipelined__DOT____Vcellout__ctr_unit1__is_load_o;
        CData/*0:0*/ top__DOT__pipelined__DOT____Vcellout__ctr_unit1__mem_wren_o;
        CData/*0:0*/ top__DOT__pipelined__DOT____Vcellout__ctr_unit1__op_b_sel_o;
        CData/*0:0*/ top__DOT__pipelined__DOT____Vcellout__ctr_unit1__op_a_sel_o;
        CData/*0:0*/ top__DOT__pipelined__DOT____Vcellout__ctr_unit1__br_unsigned_o;
        CData/*0:0*/ top__DOT__pipelined__DOT____Vcellout__ctr_unit1__rd_wren_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__br_less;
        CData/*0:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__br_equal;
        CData/*1:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_u__DOT__el_t;
        CData/*1:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_u__DOT__al_t;
        CData/*0:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_u__DOT____Vcellout__compare160__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_u__DOT____Vcellout__compare161__alarger_o;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_u__DOT__compare160__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_u__DOT__compare160__DOT__al_t;
        CData/*0:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_u__DOT__compare160__DOT____Vcellout__compare10__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_u__DOT__compare160__DOT____Vcellout__compare11__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_u__DOT__compare160__DOT____Vcellout__compare12__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_u__DOT__compare160__DOT____Vcellout__compare13__alarger_o;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_u__DOT__compare160__DOT__compare10__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_u__DOT__compare160__DOT__compare10__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_u__DOT__compare160__DOT__compare11__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_u__DOT__compare160__DOT__compare11__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_u__DOT__compare160__DOT__compare12__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_u__DOT__compare160__DOT__compare12__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_u__DOT__compare160__DOT__compare13__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_u__DOT__compare160__DOT__compare13__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_u__DOT__compare161__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_u__DOT__compare161__DOT__al_t;
        CData/*0:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_u__DOT__compare161__DOT____Vcellout__compare10__alarger_o;
    };
    struct {
        CData/*0:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_u__DOT__compare161__DOT____Vcellout__compare11__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_u__DOT__compare161__DOT____Vcellout__compare12__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_u__DOT__compare161__DOT____Vcellout__compare13__alarger_o;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_u__DOT__compare161__DOT__compare10__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_u__DOT__compare161__DOT__compare10__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_u__DOT__compare161__DOT__compare11__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_u__DOT__compare161__DOT__compare11__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_u__DOT__compare161__DOT__compare12__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_u__DOT__compare161__DOT__compare12__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_u__DOT__compare161__DOT__compare13__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_u__DOT__compare161__DOT__compare13__DOT__al_t;
        CData/*1:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__eq_t;
        CData/*1:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__al_t;
        CData/*1:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__bl_t;
        CData/*0:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT____Vcellout__compare32u_0__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT____Vcellout__compare32u_1__alarger_o;
        CData/*1:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_0__DOT__el_t;
        CData/*1:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_0__DOT__al_t;
        CData/*0:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_0__DOT____Vcellout__compare160__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_0__DOT____Vcellout__compare161__alarger_o;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_0__DOT__compare160__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_0__DOT__compare160__DOT__al_t;
        CData/*0:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_0__DOT__compare160__DOT____Vcellout__compare10__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_0__DOT__compare160__DOT____Vcellout__compare11__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_0__DOT__compare160__DOT____Vcellout__compare12__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_0__DOT__compare160__DOT____Vcellout__compare13__alarger_o;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_0__DOT__compare160__DOT__compare10__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_0__DOT__compare160__DOT__compare10__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_0__DOT__compare160__DOT__compare11__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_0__DOT__compare160__DOT__compare11__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_0__DOT__compare160__DOT__compare12__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_0__DOT__compare160__DOT__compare12__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_0__DOT__compare160__DOT__compare13__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_0__DOT__compare160__DOT__compare13__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_0__DOT__compare161__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_0__DOT__compare161__DOT__al_t;
        CData/*0:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_0__DOT__compare161__DOT____Vcellout__compare10__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_0__DOT__compare161__DOT____Vcellout__compare11__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_0__DOT__compare161__DOT____Vcellout__compare12__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_0__DOT__compare161__DOT____Vcellout__compare13__alarger_o;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_0__DOT__compare161__DOT__compare10__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_0__DOT__compare161__DOT__compare10__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_0__DOT__compare161__DOT__compare11__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_0__DOT__compare161__DOT__compare11__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_0__DOT__compare161__DOT__compare12__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_0__DOT__compare161__DOT__compare12__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_0__DOT__compare161__DOT__compare13__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_0__DOT__compare161__DOT__compare13__DOT__al_t;
        CData/*1:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_1__DOT__el_t;
        CData/*1:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_1__DOT__al_t;
        CData/*0:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_1__DOT____Vcellout__compare160__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_1__DOT____Vcellout__compare161__alarger_o;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_1__DOT__compare160__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_1__DOT__compare160__DOT__al_t;
        CData/*0:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_1__DOT__compare160__DOT____Vcellout__compare10__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_1__DOT__compare160__DOT____Vcellout__compare11__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_1__DOT__compare160__DOT____Vcellout__compare12__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_1__DOT__compare160__DOT____Vcellout__compare13__alarger_o;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_1__DOT__compare160__DOT__compare10__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_1__DOT__compare160__DOT__compare10__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_1__DOT__compare160__DOT__compare11__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_1__DOT__compare160__DOT__compare11__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_1__DOT__compare160__DOT__compare12__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_1__DOT__compare160__DOT__compare12__DOT__al_t;
    };
    struct {
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_1__DOT__compare160__DOT__compare13__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_1__DOT__compare160__DOT__compare13__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_1__DOT__compare161__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_1__DOT__compare161__DOT__al_t;
        CData/*0:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_1__DOT__compare161__DOT____Vcellout__compare10__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_1__DOT__compare161__DOT____Vcellout__compare11__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_1__DOT__compare161__DOT____Vcellout__compare12__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_1__DOT__compare161__DOT____Vcellout__compare13__alarger_o;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_1__DOT__compare161__DOT__compare10__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_1__DOT__compare161__DOT__compare10__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_1__DOT__compare161__DOT__compare11__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_1__DOT__compare161__DOT__compare11__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_1__DOT__compare161__DOT__compare12__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_1__DOT__compare161__DOT__compare12__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_1__DOT__compare161__DOT__compare13__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__brcomp1__DOT__compare32_s__DOT__compare32u_1__DOT__compare161__DOT__compare13__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__alu_op;
        CData/*4:0*/ top__DOT__pipelined__DOT__alu1__DOT__shift_amt;
        CData/*0:0*/ top__DOT__pipelined__DOT__alu1__DOT__br_less;
        CData/*0:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__br_less_s;
        CData/*0:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__br_equal_s;
        CData/*1:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_u__DOT__el_t;
        CData/*1:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_u__DOT__al_t;
        CData/*0:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_u__DOT____Vcellout__compare160__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_u__DOT____Vcellout__compare161__alarger_o;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_u__DOT__compare160__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_u__DOT__compare160__DOT__al_t;
        CData/*0:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_u__DOT__compare160__DOT____Vcellout__compare10__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_u__DOT__compare160__DOT____Vcellout__compare11__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_u__DOT__compare160__DOT____Vcellout__compare12__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_u__DOT__compare160__DOT____Vcellout__compare13__alarger_o;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_u__DOT__compare160__DOT__compare10__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_u__DOT__compare160__DOT__compare10__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_u__DOT__compare160__DOT__compare11__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_u__DOT__compare160__DOT__compare11__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_u__DOT__compare160__DOT__compare12__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_u__DOT__compare160__DOT__compare12__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_u__DOT__compare160__DOT__compare13__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_u__DOT__compare160__DOT__compare13__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_u__DOT__compare161__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_u__DOT__compare161__DOT__al_t;
        CData/*0:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_u__DOT__compare161__DOT____Vcellout__compare10__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_u__DOT__compare161__DOT____Vcellout__compare11__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_u__DOT__compare161__DOT____Vcellout__compare12__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_u__DOT__compare161__DOT____Vcellout__compare13__alarger_o;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_u__DOT__compare161__DOT__compare10__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_u__DOT__compare161__DOT__compare10__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_u__DOT__compare161__DOT__compare11__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_u__DOT__compare161__DOT__compare11__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_u__DOT__compare161__DOT__compare12__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_u__DOT__compare161__DOT__compare12__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_u__DOT__compare161__DOT__compare13__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_u__DOT__compare161__DOT__compare13__DOT__al_t;
        CData/*0:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__alarger_o;
        CData/*1:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__eq_t;
        CData/*1:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__al_t;
        CData/*1:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__bl_t;
        CData/*0:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT____Vcellout__compare32u_0__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT____Vcellout__compare32u_1__alarger_o;
        CData/*1:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_0__DOT__el_t;
        CData/*1:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_0__DOT__al_t;
        CData/*0:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_0__DOT____Vcellout__compare160__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_0__DOT____Vcellout__compare161__alarger_o;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_0__DOT__compare160__DOT__eq_t;
    };
    struct {
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_0__DOT__compare160__DOT__al_t;
        CData/*0:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_0__DOT__compare160__DOT____Vcellout__compare10__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_0__DOT__compare160__DOT____Vcellout__compare11__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_0__DOT__compare160__DOT____Vcellout__compare12__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_0__DOT__compare160__DOT____Vcellout__compare13__alarger_o;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_0__DOT__compare160__DOT__compare10__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_0__DOT__compare160__DOT__compare10__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_0__DOT__compare160__DOT__compare11__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_0__DOT__compare160__DOT__compare11__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_0__DOT__compare160__DOT__compare12__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_0__DOT__compare160__DOT__compare12__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_0__DOT__compare160__DOT__compare13__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_0__DOT__compare160__DOT__compare13__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_0__DOT__compare161__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_0__DOT__compare161__DOT__al_t;
        CData/*0:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_0__DOT__compare161__DOT____Vcellout__compare10__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_0__DOT__compare161__DOT____Vcellout__compare11__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_0__DOT__compare161__DOT____Vcellout__compare12__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_0__DOT__compare161__DOT____Vcellout__compare13__alarger_o;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_0__DOT__compare161__DOT__compare10__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_0__DOT__compare161__DOT__compare10__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_0__DOT__compare161__DOT__compare11__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_0__DOT__compare161__DOT__compare11__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_0__DOT__compare161__DOT__compare12__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_0__DOT__compare161__DOT__compare12__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_0__DOT__compare161__DOT__compare13__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_0__DOT__compare161__DOT__compare13__DOT__al_t;
        CData/*1:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_1__DOT__el_t;
        CData/*1:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_1__DOT__al_t;
        CData/*0:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_1__DOT____Vcellout__compare160__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_1__DOT____Vcellout__compare161__alarger_o;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_1__DOT__compare160__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_1__DOT__compare160__DOT__al_t;
        CData/*0:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_1__DOT__compare160__DOT____Vcellout__compare10__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_1__DOT__compare160__DOT____Vcellout__compare11__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_1__DOT__compare160__DOT____Vcellout__compare12__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_1__DOT__compare160__DOT____Vcellout__compare13__alarger_o;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_1__DOT__compare160__DOT__compare10__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_1__DOT__compare160__DOT__compare10__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_1__DOT__compare160__DOT__compare11__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_1__DOT__compare160__DOT__compare11__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_1__DOT__compare160__DOT__compare12__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_1__DOT__compare160__DOT__compare12__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_1__DOT__compare160__DOT__compare13__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_1__DOT__compare160__DOT__compare13__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_1__DOT__compare161__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_1__DOT__compare161__DOT__al_t;
        CData/*0:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_1__DOT__compare161__DOT____Vcellout__compare10__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_1__DOT__compare161__DOT____Vcellout__compare11__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_1__DOT__compare161__DOT____Vcellout__compare12__alarger_o;
        CData/*0:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_1__DOT__compare161__DOT____Vcellout__compare13__alarger_o;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_1__DOT__compare161__DOT__compare10__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_1__DOT__compare161__DOT__compare10__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_1__DOT__compare161__DOT__compare11__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_1__DOT__compare161__DOT__compare11__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_1__DOT__compare161__DOT__compare12__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_1__DOT__compare161__DOT__compare12__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_1__DOT__compare161__DOT__compare13__DOT__eq_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__alu1__DOT__brcomp2__DOT__compare32_s__DOT__compare32u_1__DOT__compare161__DOT__compare13__DOT__al_t;
        CData/*3:0*/ top__DOT__pipelined__DOT__lsu1__DOT____Vxrand_h96ff575f__0;
        IData/*31:0*/ top__DOT__pipelined__DOT__lsu1__DOT__input_peri;
        IData/*31:0*/ top__DOT__pipelined__DOT__lsu1__DOT__dataout_1;
        IData/*31:0*/ top__DOT__pipelined__DOT__lsu1__DOT__dataout_2;
        IData/*31:0*/ top__DOT__pipelined__DOT__lsu1__DOT__dataout_3;
    };
    struct {
        IData/*31:0*/ top__DOT__pipelined__DOT__lsu1__DOT__temp_ld_data;
        CData/*3:0*/ top__DOT__pipelined__DOT__lsu1__DOT__mask;
        CData/*0:0*/ top__DOT__pipelined__DOT__ctr_unit1__DOT____Vxrand_h96fefc1e__2;
        CData/*0:0*/ top__DOT__pipelined__DOT__ctr_unit1__DOT____Vxrand_h96fefc1e__1;
        CData/*0:0*/ top__DOT__pipelined__DOT__ctr_unit1__DOT____Vxrand_h96fefc1e__0;
        CData/*2:0*/ top__DOT__pipelined__DOT__ctr_unit1__DOT____Vxrand_h96ff2746__0;
        CData/*0:0*/ __Vclklast__TOP__clk_i;
        VL_IN(io_sw_i,31,0);
        VL_OUT(io_lcd_o,31,0);
        VL_OUT(io_ledg_o,31,0);
        VL_OUT(io_ledr_o,31,0);
        VL_OUT(io_hex0_o,31,0);
        VL_OUT(io_hex1_o,31,0);
        VL_OUT(io_hex2_o,31,0);
        VL_OUT(io_hex3_o,31,0);
        VL_OUT(io_hex4_o,31,0);
        VL_OUT(io_hex5_o,31,0);
        VL_OUT(io_hex6_o,31,0);
        VL_OUT(io_hex7_o,31,0);
        VL_OUT(pc_debug_o,31,0);
        IData/*31:0*/ top__DOT__pipelined__DOT__ex_alu_data;
        IData/*31:0*/ top__DOT__pipelined__DOT__mem_alu_data;
        IData/*31:0*/ top__DOT__pipelined__DOT__wb_alu_data;
        IData/*31:0*/ top__DOT__pipelined__DOT__operand_a;
        IData/*31:0*/ top__DOT__pipelined__DOT__operand_b;
        IData/*31:0*/ top__DOT__pipelined__DOT__nxt_pc;
        IData/*31:0*/ top__DOT__pipelined__DOT__imm;
        IData/*31:0*/ top__DOT__pipelined__DOT____Vcellout__id_reg1__pc_o;
        IData/*31:0*/ top__DOT__pipelined__DOT____Vcellout__id_reg1__instr_o;
        IData/*31:0*/ top__DOT__pipelined__DOT____Vcellout__ex_reg1__rs2_data_o;
        IData/*31:0*/ top__DOT__pipelined__DOT____Vcellout__ex_reg1__rs1_data_o;
        IData/*31:0*/ top__DOT__pipelined__DOT____Vcellout__ex_reg1__pc_o;
        IData/*31:0*/ top__DOT__pipelined__DOT____Vcellout__ex_reg1__instr_o;
        IData/*31:0*/ top__DOT__pipelined__DOT____Vcellout__mem_reg1__rs2_data_o;
        IData/*31:0*/ top__DOT__pipelined__DOT____Vcellout__mem_reg1__pc_o;
        IData/*31:0*/ top__DOT__pipelined__DOT____Vcellout__mem_reg1__instr_o;
        IData/*31:0*/ top__DOT__pipelined__DOT____Vcellout__wb_reg1__ld_data_o;
        IData/*31:0*/ top__DOT__pipelined__DOT____Vcellout__wb_reg1__pc_o;
        IData/*31:0*/ top__DOT__pipelined__DOT____Vcellout__wb_reg1__instr_o;
        IData/*31:0*/ top__DOT__pipelined__DOT__alu1__DOT__temp_shift;
        IData/*31:0*/ top__DOT__pipelined__DOT__alu1__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ top__DOT__pipelined__DOT__lsu1__DOT____Vxrand_h96fd10a2__0;
        VlUnpacked<CData/*0:0*/, 4> top__DOT__pipelined__DOT__enable;
        VlUnpacked<IData/*31:0*/, 5> top__DOT__pipelined__DOT__instr;
        VlUnpacked<IData/*31:0*/, 5> top__DOT__pipelined__DOT__pc;
        VlUnpacked<IData/*31:0*/, 2> top__DOT__pipelined__DOT__rs1_data;
        VlUnpacked<IData/*31:0*/, 3> top__DOT__pipelined__DOT__rs2_data;
        VlUnpacked<CData/*0:0*/, 4> top__DOT__pipelined__DOT__rd_wren;
        VlUnpacked<CData/*3:0*/, 2> top__DOT__pipelined__DOT__alu_op;
        VlUnpacked<CData/*0:0*/, 2> top__DOT__pipelined__DOT__op_a_sel;
        VlUnpacked<CData/*0:0*/, 2> top__DOT__pipelined__DOT__op_b_sel;
        VlUnpacked<CData/*2:0*/, 3> top__DOT__pipelined__DOT__mem_op;
        VlUnpacked<CData/*0:0*/, 4> top__DOT__pipelined__DOT__mem_wren;
        VlUnpacked<CData/*0:0*/, 4> top__DOT__pipelined__DOT__is_load;
        VlUnpacked<IData/*31:0*/, 2> top__DOT__pipelined__DOT__ld_data;
        VlUnpacked<IData/*31:0*/, 1> top__DOT__pipelined__DOT__wb_data;
        VlUnpacked<CData/*1:0*/, 4> top__DOT__pipelined__DOT__wb_sel;
        VlUnpacked<CData/*0:0*/, 2> top__DOT__pipelined__DOT__br_unsigned;
        VlUnpacked<CData/*0:0*/, 2> top__DOT__pipelined__DOT__is_rs2;
        VlUnpacked<IData/*31:0*/, 4096> top__DOT__pipelined__DOT__inst_memory1__DOT__memory;
        VlUnpacked<IData/*31:0*/, 32> top__DOT__pipelined__DOT__regfile1__DOT__memory;
        VlUnpacked<IData/*31:0*/, 256> top__DOT__pipelined__DOT__lsu1__DOT__memory;
        VlUnpacked<IData/*31:0*/, 64> top__DOT__pipelined__DOT__lsu1__DOT__output_peri;
        VlUnpacked<CData/*0:0*/, 3> __Vm_traceActivity;
    };

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* name);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);


#endif  // guard
